### PR TITLE
Adds ability to toggle post sorting (new/top)

### PR DESCRIPTION
**Pull request by canalesb93**
Clicking 'up' on the main card toggle sorting type between new and top. Saves las selected sorting on pebble's local storage.

### CODE REVIEW

**Comment by Antrikshy** [comment]
Is this set to top by default? Could you change it to new instead?

Also, what time period is the top sorting done by? There is not much reason to sort by top by day on this sub because there aren't many posts each day anyway and the newest 35 posts cover several days worth of posts.

**Comment by canalesb93** [comment]
I see what you mean. I think 'hot' sort would be more appropriate, I'll leave 'new' as the default sort.

**Comment by Antrikshy** [comment]
Hot would still give a very similar list but only with different ordering for a sub with such a small number of posts each day. Sorry, but I think the whole thing is kinda pointless anyway. We could do a weekly sort but I think many deals would be done by the time someone acted on them. For a sub of this nature, new sorting is the best way to go. I know you worked quite a bit on the app and I appreciate it. Maybe make another modification of some sort? I can't think of anything cool though.

**Comment by canalesb93** [comment]
It's alright, I was planning on using your code to make something similar with another subreddit where toggling between hot/top made more sense.

**Comment by Antrikshy** [comment]
I'm glad you were interested in my code for reference. If you need to, you can always ask me for help [@Antrikshy](http://twitter.com/Antrikshy). I'm not a Pebble.js expert, but as you know, I have some experience with interacting with reddit. 

:)

**Pull request closed without merging**
